mod 'puppet-nginx', '2.1.1'
mod 'puppetlabs-concat', '6.2.0'
mod 'puppetlabs-stdlib', '6.5.0'
mod 'puppetlabs-translate', '2.2.0'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '3.12.1'
